package com.rvelamen.springmvc.mapper;

import com.rvelamen.springmvc.pojo.House;
import com.rvelamen.springmvc.pojo.HouseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    House selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */

    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *更新房屋数据
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    int updateByPrimaryKey(House record);

    /**
     * 载入页面时，显示的房屋数据
     */
    List<House> selectFirst();

    /**
     * 搜索房屋类型
     */
    List<House> houseTypeSearch(String str);


    /**
     * 添加房屋数据
     */
    int addDataHouse(House record);
    ;
}