package com.rvelamen.springmvc.pojo;

import java.util.Date;

public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.location
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.quotePrice
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Float quoteprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.area
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Float area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.price
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.floorLevel
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private String floorlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.erientation
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private String erientation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.property
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Integer property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.type
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.completion
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Integer completion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.findTime
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    private Date findtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.location
     *
     * @return the value of house.location
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.location
     *
     * @param location the value for house.location
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.quotePrice
     *
     * @return the value of house.quotePrice
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Float getQuoteprice() {
        return quoteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.quotePrice
     *
     * @param quoteprice the value for house.quotePrice
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setQuoteprice(Float quoteprice) {
        this.quoteprice = quoteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.area
     *
     * @return the value of house.area
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Float getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.area
     *
     * @param area the value for house.area
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setArea(Float area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.price
     *
     * @return the value of house.price
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.price
     *
     * @param price the value for house.price
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.floorLevel
     *
     * @return the value of house.floorLevel
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public String getFloorlevel() {
        return floorlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.floorLevel
     *
     * @param floorlevel the value for house.floorLevel
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setFloorlevel(String floorlevel) {
        this.floorlevel = floorlevel == null ? null : floorlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.erientation
     *
     * @return the value of house.erientation
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public String getErientation() {
        return erientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.erientation
     *
     * @param erientation the value for house.erientation
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setErientation(String erientation) {
        this.erientation = erientation == null ? null : erientation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.property
     *
     * @return the value of house.property
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Integer getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.property
     *
     * @param property the value for house.property
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setProperty(Integer property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.type
     *
     * @return the value of house.type
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.type
     *
     * @param type the value for house.type
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.completion
     *
     * @return the value of house.completion
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Integer getCompletion() {
        return completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.completion
     *
     * @param completion the value for house.completion
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setCompletion(Integer completion) {
        this.completion = completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.findTime
     *
     * @return the value of house.findTime
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public Date getFindtime() {
        return findtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.findTime
     *
     * @param findtime the value for house.findTime
     *
     * @mbggenerated Wed Oct 03 23:07:38 IRKT 2018
     */
    public void setFindtime(Date findtime) {
        this.findtime = findtime;
    }
}